USE health_management;

-- 先删除引用了食物表的饮食记录(因为有外键约束 ON DELETE RESTRICT)
DELETE FROM diet_records;

-- 清空现有食物表数据
DELETE FROM foods;

-- 重置自增ID
ALTER TABLE diet_records AUTO_INCREMENT = 1;
ALTER TABLE foods AUTO_INCREMENT = 1;

-- 主食类 (30条)
INSERT INTO foods (name, name_en, category, category_en, sub_category, sub_category_en, calories_per_100g, protein_per_100g, fat_per_100g, carbs_per_100g, fiber_per_100g, sodium_per_100g, description, description_en, is_verified) VALUES
('白米饭', 'Steamed White Rice', '主食', 'Staple', '米类', 'Rice', 116, 2.6, 0.3, 25.9, 0.3, 2, '最常见的主食，提供碳水化合物和少量蛋白质', 'Most common staple food, provides carbohydrates and small amount of protein', TRUE),
('糙米饭', 'Brown Rice', '主食', 'Staple', '米类', 'Rice', 111, 2.6, 0.9, 23.5, 1.8, 5, '富含膳食纤维和维生素B群，营养价值高于白米', 'Rich in dietary fiber and B vitamins, more nutritious than white rice', TRUE),
('黑米饭', 'Black Rice', '主食', 'Staple', '米类', 'Rice', 341, 8.5, 2.5, 72.2, 3.9, 4, '富含花青素和铁质，具有抗氧化作用', 'Rich in anthocyanins and iron, has antioxidant properties', TRUE),
('紫米饭', 'Purple Rice', '主食', 'Staple', '米类', 'Rice', 356, 9.1, 2.8, 75.5, 4.2, 6, '含有丰富的花青素和膳食纤维', 'Contains abundant anthocyanins and dietary fiber', TRUE),
('糯米饭', 'Glutinous Rice', '主食', 'Staple', '米类', 'Rice', 116, 2.5, 0.2, 26.3, 0.4, 3, '黏性较强，消化较快，适合制作传统点心', 'Sticky texture, digests quickly, suitable for traditional desserts', TRUE),
('白面条', 'White Noodles', '主食', 'Staple', '面类', 'Noodles', 137, 4.5, 0.5, 28.5, 1.2, 200, '由小麦粉制成，口感爽滑', 'Made from wheat flour, smooth texture', TRUE),
('全麦面条', 'Whole Wheat Noodles', '主食', 'Staple', '面类', 'Noodles', 124, 5.0, 0.8, 25.3, 3.5, 180, '保留麦麸，富含膳食纤维和B族维生素', 'Retains wheat bran, rich in dietary fiber and B vitamins', TRUE),
('荞麦面', 'Soba Noodles', '主食', 'Staple', '面类', 'Noodles', 99, 4.5, 0.5, 21.4, 2.0, 25, '富含芦丁和膳食纤维，有助于降血脂', 'Rich in rutin and dietary fiber, helps lower blood lipids', TRUE),
('意大利面', 'Pasta', '主食', 'Staple', '面类', 'Noodles', 131, 5.0, 0.5, 25.0, 1.8, 6, '硬质小麦制成，GI值较低', 'Made from durum wheat, lower GI value', TRUE),
('乌冬面', 'Udon Noodles', '主食', 'Staple', '面类', 'Noodles', 131, 3.5, 0.4, 28.2, 1.0, 220, '日式粗面条，口感Q弹', 'Japanese thick noodles, chewy texture', TRUE),
('白面包', 'White Bread', '主食', 'Staple', '面包', 'Bread', 265, 8.9, 3.2, 49.0, 2.7, 491, '常见早餐面包，易消化', 'Common breakfast bread, easy to digest', TRUE),
('全麦面包', 'Whole Wheat Bread', '主食', 'Staple', '面包', 'Bread', 247, 9.2, 3.4, 41.3, 6.9, 400, '富含膳食纤维，饱腹感强', 'Rich in dietary fiber, very filling', TRUE),
('黑麦面包', 'Rye Bread', '主食', 'Staple', '面包', 'Bread', 259, 8.5, 3.3, 48.3, 5.8, 603, '欧式面包，营养价值高', 'European style bread, high nutritional value', TRUE),
('法棍', 'Baguette', '主食', 'Staple', '面包', 'Bread', 274, 9.0, 2.0, 55.0, 2.3, 620, '法式传统面包，外脆内软', 'Traditional French bread, crispy outside and soft inside', TRUE),
('贝果', 'Bagel', '主食', 'Staple', '面包', 'Bread', 257, 10.1, 1.7, 50.9, 2.3, 430, '犹太传统面包，需先煮后烤', 'Traditional Jewish bread, boiled then baked', TRUE),
('燕麦片', 'Oatmeal', '主食', 'Staple', '杂粮', 'Whole Grains', 367, 13.2, 6.5, 66.3, 10.1, 2, '富含β-葡聚糖，有助于降低胆固醇', 'Rich in beta-glucan, helps lower cholesterol', TRUE),
('小米粥', 'Millet Porridge', '主食', 'Staple', '杂粮', 'Whole Grains', 46, 1.5, 0.4, 9.0, 0.7, 1, '易消化，适合养胃', 'Easy to digest, good for stomach health', TRUE),
('薏米', 'Job\'s Tears', '主食', 'Staple', '杂粮', 'Whole Grains', 357, 12.8, 3.3, 71.1, 2.0, 3, '有利水消肿功效，富含蛋白质', 'Has diuretic effects, rich in protein', TRUE),
('藜麦', 'Quinoa', '主食', 'Staple', '杂粮', 'Whole Grains', 368, 14.1, 6.1, 64.2, 7.0, 5, '完全蛋白质来源，营养均衡', 'Complete protein source, nutritionally balanced', TRUE),
('高粱米', 'Sorghum', '主食', 'Staple', '杂粮', 'Whole Grains', 351, 10.4, 3.1, 74.6, 4.3, 6, '富含单宁和酚类化合物，抗氧化', 'Rich in tannins and phenolic compounds, antioxidant', TRUE),
('玉米', 'Corn', '主食', 'Staple', '杂粮', 'Whole Grains', 112, 4.0, 1.2, 23.2, 2.9, 1, '富含叶黄素和玉米黄质，保护眼睛', 'Rich in lutein and zeaxanthin, protects eyes', TRUE),
('红薯', 'Sweet Potato', '主食', 'Staple', '薯类', 'Tubers', 86, 1.6, 0.2, 20.1, 3.0, 55, '富含β-胡萝卜素和膳食纤维', 'Rich in beta-carotene and dietary fiber', TRUE),
('紫薯', 'Purple Sweet Potato', '主食', 'Staple', '薯类', 'Tubers', 82, 1.5, 0.2, 18.7, 2.3, 40, '富含花青素，抗氧化能力强', 'Rich in anthocyanins, strong antioxidant capacity', TRUE),
('土豆', 'Potato', '主食', 'Staple', '薯类', 'Tubers', 76, 2.0, 0.2, 17.2, 2.1, 5, '富含钾和维生素C，饱腹感强', 'Rich in potassium and vitamin C, very filling', TRUE),
('芋头', 'Taro', '主食', 'Staple', '薯类', 'Tubers', 79, 1.5, 0.2, 18.1, 1.0, 28, '口感软糯，富含黏液蛋白', 'Soft and sticky texture, rich in mucilage protein', TRUE),
('山药', 'Chinese Yam', '主食', 'Staple', '薯类', 'Tubers', 56, 1.9, 0.2, 12.4, 0.8, 16, '健脾养胃，富含薯蓣皂苷', 'Strengthens spleen and stomach, rich in diosgenin', TRUE),
('馒头', 'Steamed Bun', '主食', 'Staple', '面食', 'Wheat Products', 223, 7.0, 1.1, 47.0, 1.8, 230, '中式传统主食，松软可口', 'Traditional Chinese staple, soft and tasty', TRUE),
('花卷', 'Steamed Twisted Roll', '主食', 'Staple', '面食', 'Wheat Products', 214, 6.5, 2.8, 43.2, 1.5, 280, '层次分明的中式面点', 'Layered Chinese steamed roll', TRUE),
('包子', 'Steamed Bun with Filling', '主食', 'Staple', '面食', 'Wheat Products', 186, 7.8, 3.5, 32.0, 1.2, 350, '带馅料的中式面点，营养丰富', 'Chinese steamed bun with filling, nutritious', TRUE),
('饺子皮', 'Dumpling Wrapper', '主食', 'Staple', '面食', 'Wheat Products', 240, 8.2, 1.5, 48.5, 1.8, 200, '用于包制饺子的面皮', 'Wrapper used for making dumplings', TRUE),

-- 蔬菜类 (40条)
('菠菜', 'Spinach', '蔬菜', 'Vegetable', '叶菜', 'Leafy Greens', 23, 2.9, 0.3, 3.6, 2.2, 79, '富含铁和叶酸，深绿色叶菜', 'Rich in iron and folate, dark leafy green', TRUE),
('小白菜', 'Baby Bok Choy', '蔬菜', 'Vegetable', '叶菜', 'Leafy Greens', 13, 1.5, 0.2, 2.2, 1.1, 73, '清淡爽口，富含维生素C', 'Light and refreshing, rich in vitamin C', TRUE),
('生菜', 'Lettuce', '蔬菜', 'Vegetable', '叶菜', 'Leafy Greens', 15, 1.4, 0.2, 2.8, 1.3, 28, '常用于沙拉，水分含量高', 'Commonly used in salads, high water content', TRUE),
('油麦菜', 'Chinese Lettuce', '蔬菜', 'Vegetable', '叶菜', 'Leafy Greens', 12, 1.4, 0.3, 1.8, 0.6, 36, '口感脆嫩，略带苦味', 'Crisp texture, slightly bitter', TRUE),
('芹菜', 'Celery', '蔬菜', 'Vegetable', '叶菜', 'Leafy Greens', 12, 0.7, 0.1, 2.6, 1.6, 80, '富含膳食纤维，有助于降血压', 'Rich in dietary fiber, helps lower blood pressure', TRUE),
('芥蓝', 'Chinese Kale', '蔬菜', 'Vegetable', '叶菜', 'Leafy Greens', 19, 2.0, 0.3, 3.0, 1.6, 31, '营养价值高，口感略苦', 'High nutritional value, slightly bitter taste', TRUE),
('韭菜', 'Chinese Chives', '蔬菜', 'Vegetable', '叶菜', 'Leafy Greens', 26, 2.4, 0.4, 4.6, 1.4, 8, '有特殊香味，富含维生素', 'Distinctive aroma, rich in vitamins', TRUE),
('茼蒿', 'Crown Daisy', '蔬菜', 'Vegetable', '叶菜', 'Leafy Greens', 21, 1.9, 0.3, 3.9, 1.2, 161, '特殊香味，营养丰富', 'Unique aroma, nutritious', TRUE),
('空心菜', 'Water Spinach', '蔬菜', 'Vegetable', '叶菜', 'Leafy Greens', 20, 2.2, 0.2, 3.1, 2.2, 94, '茎空心，富含膳食纤维', 'Hollow stem, rich in dietary fiber', TRUE),
('西兰花', 'Broccoli', '蔬菜', 'Vegetable', '花菜', 'Cruciferous', 34, 2.8, 0.4, 6.6, 2.6, 33, '富含维生素C和硫化物，抗癌蔬菜', 'Rich in vitamin C and sulfur compounds, anti-cancer vegetable', TRUE),
('花菜', 'Cauliflower', '蔬菜', 'Vegetable', '花菜', 'Cruciferous', 24, 1.9, 0.2, 4.9, 2.0, 30, '低热量，富含维生素C', 'Low calorie, rich in vitamin C', TRUE),
('卷心菜', 'Cabbage', '蔬菜', 'Vegetable', '花菜', 'Cruciferous', 25, 1.3, 0.1, 5.8, 2.5, 18, '富含维生素K和C，耐储存', 'Rich in vitamins K and C, good storage', TRUE),
('紫甘蓝', 'Purple Cabbage', '蔬菜', 'Vegetable', '花菜', 'Cruciferous', 31, 1.4, 0.2, 7.4, 2.1, 27, '富含花青素，抗氧化', 'Rich in anthocyanins, antioxidant', TRUE),
('萝卜', 'Radish', '蔬菜', 'Vegetable', '根茎', 'Root Vegetables', 16, 0.9, 0.1, 3.4, 1.6, 69, '助消化，富含维生素C', 'Aids digestion, rich in vitamin C', TRUE),
('胡萝卜', 'Carrot', '蔬菜', 'Vegetable', '根茎', 'Root Vegetables', 41, 0.9, 0.2, 9.6, 2.8, 69, '富含β-胡萝卜素，保护视力', 'Rich in beta-carotene, protects eyesight', TRUE),
('莲藕', 'Lotus Root', '蔬菜', 'Vegetable', '根茎', 'Root Vegetables', 74, 2.0, 0.1, 16.4, 4.9, 44, '富含膳食纤维和维生素C', 'Rich in dietary fiber and vitamin C', TRUE),
('竹笋', 'Bamboo Shoot', '蔬菜', 'Vegetable', '根茎', 'Root Vegetables', 19, 2.6, 0.2, 3.2, 2.8, 3, '低热量，富含膳食纤维', 'Low calorie, rich in dietary fiber', TRUE),
('洋葱', 'Onion', '蔬菜', 'Vegetable', '根茎', 'Root Vegetables', 39, 1.1, 0.1, 9.0, 1.7, 4, '富含硫化物，有抗菌作用', 'Rich in sulfur compounds, antibacterial', TRUE),
('番茄', 'Tomato', '蔬菜', 'Vegetable', '茄果', 'Solanaceous', 18, 0.9, 0.2, 3.9, 1.2, 5, '富含番茄红素，抗氧化', 'Rich in lycopene, antioxidant', TRUE),
('茄子', 'Eggplant', '蔬菜', 'Vegetable', '茄果', 'Solanaceous', 21, 1.0, 0.1, 4.9, 3.0, 2, '富含花青素，保护心血管', 'Rich in anthocyanins, protects cardiovascular', TRUE),
('青椒', 'Green Pepper', '蔬菜', 'Vegetable', '茄果', 'Solanaceous', 22, 1.0, 0.2, 5.3, 1.4, 3, '富含维生素C，清脆爽口', 'Rich in vitamin C, crisp and refreshing', TRUE),
('红椒', 'Red Bell Pepper', '蔬菜', 'Vegetable', '茄果', 'Solanaceous', 31, 1.0, 0.3, 7.1, 2.1, 4, '维生素C含量极高，色泽鲜艳', 'Very high in vitamin C, bright color', TRUE),
('黄瓜', 'Cucumber', '蔬菜', 'Vegetable', '瓜类', 'Melons', 15, 0.7, 0.2, 3.6, 0.5, 2, '水分含量高，清热解暑', 'High water content, cooling effect', TRUE),
('冬瓜', 'Winter Melon', '蔬菜', 'Vegetable', '瓜类', 'Melons', 11, 0.4, 0.1, 2.6, 0.9, 2, '利尿消肿，低热量', 'Diuretic effect, low calorie', TRUE),
('南瓜', 'Pumpkin', '蔬菜', 'Vegetable', '瓜类', 'Melons', 26, 1.0, 0.1, 6.5, 0.5, 1, '富含β-胡萝卜素，保护眼睛', 'Rich in beta-carotene, protects eyes', TRUE),
('苦瓜', 'Bitter Melon', '蔬菜', 'Vegetable', '瓜类', 'Melons', 19, 1.0, 0.1, 4.3, 2.6, 5, '清热降火，有助于控制血糖', 'Cooling effect, helps control blood sugar', TRUE),
('丝瓜', 'Loofah', '蔬菜', 'Vegetable', '瓜类', 'Melons', 20, 1.0, 0.2, 4.3, 0.7, 2, '清热解毒，通络活血', 'Heat-clearing, promotes blood circulation', TRUE),
('蘑菇', 'Button Mushroom', '蔬菜', 'Vegetable', '菌类', 'Mushrooms', 22, 3.1, 0.3, 3.3, 1.0, 5, '富含蛋白质和多糖，增强免疫', 'Rich in protein and polysaccharides, boosts immunity', TRUE),
('香菇', 'Shiitake Mushroom', '蔬菜', 'Vegetable', '菌类', 'Mushrooms', 34, 2.2, 0.3, 7.3, 3.3, 9, '富含香菇多糖，营养价值高', 'Rich in lentinan, high nutritional value', TRUE),
('金针菇', 'Enoki Mushroom', '蔬菜', 'Vegetable', '菌类', 'Mushrooms', 26, 2.7, 0.4, 5.1, 2.7, 4, '细长柔软，富含赖氨酸', 'Long and slender, rich in lysine', TRUE),
('平菇', 'Oyster Mushroom', '蔬菜', 'Vegetable', '菌类', 'Mushrooms', 20, 2.0, 0.4, 4.0, 1.3, 62, '肉质肥厚，营养丰富', 'Thick and meaty, nutritious', TRUE),
('木耳', 'Wood Ear Mushroom', '蔬菜', 'Vegetable', '菌类', 'Mushrooms', 27, 1.5, 0.2, 6.5, 6.5, 48, '富含铁和膳食纤维', 'Rich in iron and dietary fiber', TRUE),
('银耳', 'White Fungus', '蔬菜', 'Vegetable', '菌类', 'Mushrooms', 261, 10.0, 1.4, 67.3, 30.4, 82, '富含胶质，滋阴润肺', 'Rich in collagen, moistens lungs', TRUE),
('豆芽', 'Bean Sprouts', '蔬菜', 'Vegetable', '芽菜', 'Sprouts', 18, 2.2, 0.2, 2.6, 1.5, 4, '鲜嫩爽脆，富含维生素C', 'Fresh and crispy, rich in vitamin C', TRUE),
('豌豆苗', 'Pea Shoots', '蔬菜', 'Vegetable', '芽菜', 'Sprouts', 35, 3.0, 0.4, 6.0, 2.8, 4, '嫩叶嫩茎，营养丰富', 'Young leaves and stems, nutritious', TRUE),
('大蒜', 'Garlic', '蔬菜', 'Vegetable', '调味菜', 'Seasoning Vegetables', 126, 4.5, 0.2, 27.6, 2.1, 5, '富含大蒜素，抗菌消炎', 'Rich in allicin, antibacterial and anti-inflammatory', TRUE),
('生姜', 'Ginger', '蔬菜', 'Vegetable', '调味菜', 'Seasoning Vegetables', 41, 1.8, 0.8, 8.8, 2.0, 13, '温中散寒，促进消化', 'Warming effect, promotes digestion', TRUE),
('香菜', 'Cilantro', '蔬菜', 'Vegetable', '调味菜', 'Seasoning Vegetables', 23, 2.1, 0.5, 3.7, 2.8, 46, '特殊香味，富含维生素', 'Distinctive aroma, rich in vitamins', TRUE),
('葱', 'Scallion', '蔬菜', 'Vegetable', '调味菜', 'Seasoning Vegetables', 30, 1.7, 0.3, 6.5, 2.5, 5, '提味增香，富含硫化物', 'Enhances flavor, rich in sulfur compounds', TRUE),
('秋葵', 'Okra', '蔬菜', 'Vegetable', '其他', 'Others', 37, 2.0, 0.1, 7.5, 3.2, 7, '富含黏液蛋白，保护肠胃', 'Rich in mucilage protein, protects digestive system', TRUE),

-- 水果类 (40条)
('苹果', 'Apple', '水果', 'Fruit', '仁果', 'Pome Fruits', 52, 0.3, 0.2, 13.8, 2.4, 1, '富含果胶和维生素C，常见水果', 'Rich in pectin and vitamin C, common fruit', TRUE),
('梨', 'Pear', '水果', 'Fruit', '仁果', 'Pome Fruits', 44, 0.4, 0.1, 11.3, 3.1, 2, '清热润肺，水分含量高', 'Cooling effect, high water content', TRUE),
('山楂', 'Hawthorn', '水果', 'Fruit', '仁果', 'Pome Fruits', 95, 0.8, 0.6, 22.1, 5.4, 5, '助消化，富含黄酮类化合物', 'Aids digestion, rich in flavonoids', TRUE),
('枇杷', 'Loquat', '水果', 'Fruit', '仁果', 'Pome Fruits', 41, 0.4, 0.2, 10.5, 0.8, 3, '润肺止咳，富含胡萝卜素', 'Soothes lungs and cough, rich in carotene', TRUE),
('草莓', 'Strawberry', '水果', 'Fruit', '浆果', 'Berries', 32, 0.7, 0.2, 7.7, 2.0, 1, '富含维生素C和花青素', 'Rich in vitamin C and anthocyanins', TRUE),
('蓝莓', 'Blueberry', '水果', 'Fruit', '浆果', 'Berries', 57, 0.7, 0.3, 14.5, 2.4, 1, '抗氧化能力强，保护视力', 'Strong antioxidant, protects eyesight', TRUE),
('树莓', 'Raspberry', '水果', 'Fruit', '浆果', 'Berries', 52, 1.2, 0.7, 11.9, 6.5, 1, '富含花青素和膳食纤维', 'Rich in anthocyanins and dietary fiber', TRUE),
('黑莓', 'Blackberry', '水果', 'Fruit', '浆果', 'Berries', 43, 1.4, 0.5, 9.6, 5.3, 1, '维生素C和K含量高', 'High in vitamins C and K', TRUE),
('葡萄', 'Grape', '水果', 'Fruit', '浆果', 'Berries', 69, 0.7, 0.4, 17.2, 0.9, 2, '富含白藜芦醇，抗氧化', 'Rich in resveratrol, antioxidant', TRUE),
('提子', 'Red Globe Grape', '水果', 'Fruit', '浆果', 'Berries', 69, 0.6, 0.3, 17.3, 0.7, 2, '皮薄肉脆，糖分含量高', 'Thin skin and crispy, high sugar content', TRUE),
('猕猴桃', 'Kiwi', '水果', 'Fruit', '浆果', 'Berries', 61, 1.1, 0.5, 14.7, 3.0, 3, '维生素C含量极高，助消化', 'Very high in vitamin C, aids digestion', TRUE),
('桑葚', 'Mulberry', '水果', 'Fruit', '浆果', 'Berries', 43, 1.4, 0.4, 9.8, 1.7, 10, '富含花青素和铁质', 'Rich in anthocyanins and iron', TRUE),
('橙子', 'Orange', '水果', 'Fruit', '柑橘', 'Citrus', 47, 0.9, 0.1, 11.8, 2.4, 1, '富含维生素C，增强免疫力', 'Rich in vitamin C, boosts immunity', TRUE),
('柚子', 'Pomelo', '水果', 'Fruit', '柑橘', 'Citrus', 38, 0.8, 0.1, 9.5, 1.0, 3, '降火解腻，富含维生素', 'Cooling effect, rich in vitamins', TRUE),
('柠檬', 'Lemon', '水果', 'Fruit', '柑橘', 'Citrus', 35, 1.1, 0.3, 11.0, 2.8, 2, '富含维生素C和柠檬酸', 'Rich in vitamin C and citric acid', TRUE),
('金桔', 'Kumquat', '水果', 'Fruit', '柑橘', 'Citrus', 71, 1.9, 0.9, 15.9, 6.5, 10, '连皮食用，富含维生素C', 'Eaten with peel, rich in vitamin C', TRUE),
('橘子', 'Mandarin', '水果', 'Fruit', '柑橘', 'Citrus', 44, 0.8, 0.2, 11.2, 1.8, 2, '易剥皮，富含类胡萝卜素', 'Easy to peel, rich in carotenoids', TRUE),
('柑', 'Tangerine', '水果', 'Fruit', '柑橘', 'Citrus', 44, 0.7, 0.2, 11.5, 1.7, 1, '香甜多汁，维生素丰富', 'Sweet and juicy, rich in vitamins', TRUE),
('西瓜', 'Watermelon', '水果', 'Fruit', '瓜类', 'Melons', 30, 0.6, 0.2, 7.6, 0.4, 1, '清热解暑，水分含量极高', 'Cooling effect, very high water content', TRUE),
('哈密瓜', 'Cantaloupe', '水果', 'Fruit', '瓜类', 'Melons', 34, 0.8, 0.2, 8.3, 0.9, 16, '香甜可口，富含β-胡萝卜素', 'Sweet and fragrant, rich in beta-carotene', TRUE),
('香瓜', 'Muskmelon', '水果', 'Fruit', '瓜类', 'Melons', 26, 0.6, 0.1, 6.2, 0.8, 8, '清爽解暑，热量低', 'Refreshing, low calorie', TRUE),
('香蕉', 'Banana', '水果', 'Fruit', '热带水果', 'Tropical Fruits', 91, 1.4, 0.2, 22.8, 2.6, 1, '富含钾，提供快速能量', 'Rich in potassium, provides quick energy', TRUE),
('芒果', 'Mango', '水果', 'Fruit', '热带水果', 'Tropical Fruits', 60, 0.8, 0.4, 15.2, 1.6, 2, '富含β-胡萝卜素，香甜多汁', 'Rich in beta-carotene, sweet and juicy', TRUE),
('菠萝', 'Pineapple', '水果', 'Fruit', '热带水果', 'Tropical Fruits', 50, 0.5, 0.1, 13.1, 1.4, 1, '富含菠萝蛋白酶，助消化', 'Rich in bromelain, aids digestion', TRUE),
('木瓜', 'Papaya', '水果', 'Fruit', '热带水果', 'Tropical Fruits', 43, 0.5, 0.3, 10.8, 1.7, 8, '富含木瓜酶，美容养颜', 'Rich in papain, good for skin', TRUE),
('榴莲', 'Durian', '水果', 'Fruit', '热带水果', 'Tropical Fruits', 147, 2.6, 3.3, 27.1, 3.8, 2, '营养丰富，高热量水果', 'Highly nutritious, high calorie fruit', TRUE),
('火龙果', 'Dragon Fruit', '水果', 'Fruit', '热带水果', 'Tropical Fruits', 51, 1.1, 0.2, 13.3, 1.8, 35, '富含花青素和植物性蛋白', 'Rich in anthocyanins and plant protein', TRUE),
('椰子', 'Coconut', '水果', 'Fruit', '热带水果', 'Tropical Fruits', 241, 2.3, 23.8, 6.2, 7.3, 20, '富含中链脂肪酸，清凉解渴', 'Rich in MCT, refreshing', TRUE),
('番石榴', 'Guava', '水果', 'Fruit', '热带水果', 'Tropical Fruits', 68, 2.6, 1.0, 14.3, 5.4, 2, '维生素C含量极高', 'Very high in vitamin C', TRUE),
('桃子', 'Peach', '水果', 'Fruit', '核果', 'Stone Fruits', 42, 0.9, 0.3, 10.9, 1.5, 0, '富含铁和维生素C，鲜甜多汁', 'Rich in iron and vitamin C, sweet and juicy', TRUE),
('李子', 'Plum', '水果', 'Fruit', '核果', 'Stone Fruits', 46, 0.7, 0.3, 11.4, 1.4, 0, '促进消化，富含花青素', 'Aids digestion, rich in anthocyanins', TRUE),
('樱桃', 'Cherry', '水果', 'Fruit', '核果', 'Stone Fruits', 63, 1.1, 0.2, 16.0, 2.1, 0, '富含花青素和铁质', 'Rich in anthocyanins and iron', TRUE),
('杏', 'Apricot', '水果', 'Fruit', '核果', 'Stone Fruits', 48, 1.4, 0.4, 11.1, 2.0, 1, '富含β-胡萝卜素和钾', 'Rich in beta-carotene and potassium', TRUE),
('枣', 'Jujube', '水果', 'Fruit', '核果', 'Stone Fruits', 79, 1.2, 0.2, 20.2, 1.9, 1, '富含维生素C，补血养颜', 'Rich in vitamin C, nourishes blood', TRUE),
('柿子', 'Persimmon', '水果', 'Fruit', '其他', 'Others', 71, 0.4, 0.1, 18.6, 3.6, 1, '富含胡萝卜素和鞣质', 'Rich in carotene and tannins', TRUE),
('石榴', 'Pomegranate', '水果', 'Fruit', '其他', 'Others', 83, 1.7, 1.2, 18.7, 4.0, 3, '富含多酚和花青素', 'Rich in polyphenols and anthocyanins', TRUE),
('无花果', 'Fig', '水果', 'Fruit', '其他', 'Others', 74, 0.8, 0.3, 19.2, 2.9, 10, '富含膳食纤维和矿物质', 'Rich in dietary fiber and minerals', TRUE),
('荔枝', 'Lychee', '水果', 'Fruit', '其他', 'Others', 66, 0.8, 0.4, 16.5, 1.3, 1, '富含维生素C，鲜甜多汁', 'Rich in vitamin C, sweet and juicy', TRUE),
('龙眼', 'Longan', '水果', 'Fruit', '其他', 'Others', 71, 1.3, 0.1, 17.0, 1.1, 3, '补血安神，富含铁质', 'Nourishes blood and calms nerves, rich in iron', TRUE),
('杨梅', 'Bayberry', '水果', 'Fruit', '其他', 'Others', 28, 0.8, 0.2, 6.7, 1.0, 2, '富含花青素和有机酸', 'Rich in anthocyanins and organic acids', TRUE),

-- 肉类 (30条)
('猪瘦肉', 'Lean Pork', '肉类', 'Meat', '畜肉', 'Livestock', 143, 20.3, 6.2, 1.5, 0, 65, '优质蛋白来源，富含铁和锌', 'Good protein source, rich in iron and zinc', TRUE),
('猪里脊', 'Pork Tenderloin', '肉类', 'Meat', '畜肉', 'Livestock', 155, 20.2, 7.9, 1.1, 0, 55, '肉质细嫩，脂肪含量低', 'Tender meat, low fat content', TRUE),
('猪排骨', 'Pork Ribs', '肉类', 'Meat', '畜肉', 'Livestock', 264, 17.4, 20.4, 1.8, 0, 51, '富含钙质和骨胶原', 'Rich in calcium and collagen', TRUE),
('猪蹄', 'Pig\'s Trotters', '肉类', 'Meat', '畜肉', 'Livestock', 260, 23.6, 18.8, 0, 0, 101, '富含胶原蛋白，美容养颜', 'Rich in collagen, good for skin', TRUE),
('牛肉', 'Beef', '肉类', 'Meat', '畜肉', 'Livestock', 125, 20.0, 4.2, 2.0, 0, 84, '高蛋白低脂肪，富含铁质', 'High protein low fat, rich in iron', TRUE),
('牛腱', 'Beef Shank', '肉类', 'Meat', '畜肉', 'Livestock', 106, 23.3, 1.2, 0.2, 0, 58, '低脂高蛋白，适合健身', 'Low fat high protein, good for fitness', TRUE),
('牛腩', 'Beef Brisket', '肉类', 'Meat', '畜肉', 'Livestock', 125, 19.9, 4.6, 0.3, 0, 63, '肉质松软，适合炖煮', 'Tender meat, suitable for stewing', TRUE),
('牛排', 'Beef Steak', '肉类', 'Meat', '畜肉', 'Livestock', 125, 22.3, 3.7, 0, 0, 55, '优质蛋白，口感鲜嫩', 'High quality protein, tender texture', TRUE),
('羊肉', 'Mutton', '肉类', 'Meat', '畜肉', 'Livestock', 203, 19.0, 14.1, 0, 0, 92, '温补，富含左旋肉碱', 'Warming effect, rich in L-carnitine', TRUE),
('羊腿肉', 'Lamb Leg', '肉类', 'Meat', '畜肉', 'Livestock', 118, 21.3, 3.9, 0, 0, 75, '肉质细嫩，营养丰富', 'Tender meat, nutritious', TRUE),
('鸡胸肉', 'Chicken Breast', '肉类', 'Meat', '禽肉', 'Poultry', 133, 19.4, 5.0, 2.5, 0, 63, '高蛋白低脂肪，健身首选', 'High protein low fat, ideal for fitness', TRUE),
('鸡腿肉', 'Chicken Thigh', '肉类', 'Meat', '禽肉', 'Poultry', 181, 16.0, 13.0, 0, 0, 88, '肉质鲜嫩，脂肪含量适中', 'Tender and juicy, moderate fat content', TRUE),
('鸡翅', 'Chicken Wings', '肉类', 'Meat', '禽肉', 'Poultry', 194, 17.4, 11.8, 4.6, 0, 69, '富含胶原蛋白', 'Rich in collagen', TRUE),
('鸡爪', 'Chicken Feet', '肉类', 'Meat', '禽肉', 'Poultry', 254, 23.9, 16.4, 2.7, 0, 103, '富含胶原蛋白和钙质', 'Rich in collagen and calcium', TRUE),
('鸭肉', 'Duck Meat', '肉类', 'Meat', '禽肉', 'Poultry', 240, 15.5, 19.7, 0, 0, 69, '滋阴养胃，富含B族维生素', 'Nourishing, rich in B vitamins', TRUE),
('鹅肉', 'Goose Meat', '肉类', 'Meat', '禽肉', 'Poultry', 251, 17.9, 19.9, 0, 0, 108, '补气养血，富含蛋白质', 'Nourishing, rich in protein', TRUE),
('鸽子肉', 'Pigeon Meat', '肉类', 'Meat', '禽肉', 'Poultry', 201, 16.5, 14.2, 0.9, 0, 45, '营养丰富，易消化', 'Highly nutritious, easy to digest', TRUE),
('鲈鱼', 'Sea Bass', '肉类', 'Meat', '水产', 'Seafood', 105, 18.6, 3.1, 0, 0, 55, '肉质鲜嫩，富含优质蛋白', 'Tender meat, rich in quality protein', TRUE),
('鲫鱼', 'Crucian Carp', '肉类', 'Meat', '水产', 'Seafood', 108, 13.0, 2.7, 3.8, 0, 41, '营养丰富，适合煲汤', 'Nutritious, good for soup', TRUE),
('三文鱼', 'Salmon', '肉类', 'Meat', '水产', 'Seafood', 139, 19.8, 6.3, 0, 0, 59, '富含Omega-3脂肪酸', 'Rich in Omega-3 fatty acids', TRUE),
('金枪鱼', 'Tuna', '肉类', 'Meat', '水产', 'Seafood', 132, 28.0, 0.6, 0, 0, 47, '高蛋白低脂肪', 'High protein low fat', TRUE),
('鳕鱼', 'Cod', '肉类', 'Meat', '水产', 'Seafood', 88, 20.4, 0.7, 0, 0, 121, '低脂高蛋白，肉质细嫩', 'Low fat high protein, tender meat', TRUE),
('虾', 'Shrimp', '肉类', 'Meat', '水产', 'Seafood', 93, 18.6, 1.5, 2.8, 0, 165, '富含优质蛋白和钙质', 'Rich in quality protein and calcium', TRUE),
('螃蟹', 'Crab', '肉类', 'Meat', '水产', 'Seafood', 95, 17.5, 1.6, 2.3, 0, 193, '肉质鲜美，富含蛋白质', 'Delicious meat, rich in protein', TRUE),
('扇贝', 'Scallop', '肉类', 'Meat', '水产', 'Seafood', 60, 12.0, 0.4, 2.6, 0, 74, '低脂高蛋白，富含锌', 'Low fat high protein, rich in zinc', TRUE),
('牡蛎', 'Oyster', '肉类', 'Meat', '水产', 'Seafood', 57, 9.4, 1.3, 3.0, 0, 270, '富含锌，滋阴补肾', 'Rich in zinc, nourishing', TRUE),
('鱿鱼', 'Squid', '肉类', 'Meat', '水产', 'Seafood', 92, 15.1, 1.4, 3.8, 0, 165, '富含牛磺酸和蛋白质', 'Rich in taurine and protein', TRUE),
('墨鱼', 'Cuttlefish', '肉类', 'Meat', '水产', 'Seafood', 83, 15.2, 0.9, 3.4, 0, 142, '富含蛋白质和铁质', 'Rich in protein and iron', TRUE),
('海参', 'Sea Cucumber', '肉类', 'Meat', '水产', 'Seafood', 78, 16.5, 0.2, 2.5, 0, 153, '高蛋白低脂肪，滋补佳品', 'High protein low fat, nourishing delicacy', TRUE),
('带鱼', 'Hairtail', '肉类', 'Meat', '水产', 'Seafood', 127, 17.7, 4.9, 3.1, 0, 150, '富含不饱和脂肪酸', 'Rich in unsaturated fatty acids', TRUE),

-- 蛋类 (10条)
('鸡蛋', 'Chicken Egg', '蛋类', 'Eggs', '蛋类', 'Eggs', 147, 13.3, 8.8, 2.8, 0, 131, '完全蛋白质来源，营养均衡', 'Complete protein source, nutritionally balanced', TRUE),
('鸭蛋', 'Duck Egg', '蛋类', 'Eggs', '蛋类', 'Eggs', 180, 12.6, 13.0, 3.1, 0, 106, '富含矿物质，营养价值高', 'Rich in minerals, high nutritional value', TRUE),
('鹅蛋', 'Goose Egg', '蛋类', 'Eggs', '蛋类', 'Eggs', 196, 11.1, 15.6, 2.8, 0, 90, '个头大，营养丰富', 'Large size, highly nutritious', TRUE),
('鹌鹑蛋', 'Quail Egg', '蛋类', 'Eggs', '蛋类', 'Eggs', 160, 12.8, 11.1, 2.1, 0, 138, '营养密度高，适合儿童', 'High nutrient density, good for children', TRUE),
('皮蛋', 'Century Egg', '蛋类', 'Eggs', '蛋类', 'Eggs', 171, 13.7, 10.7, 4.5, 0, 542, '特殊风味，富含矿物质', 'Unique flavor, rich in minerals', TRUE),
('咸鸭蛋', 'Salted Duck Egg', '蛋类', 'Eggs', '蛋类', 'Eggs', 190, 12.7, 13.9, 4.7, 0, 2706, '蛋黄红亮，下饭佳品', 'Bright red yolk, good with rice', TRUE),
('茶叶蛋', 'Tea Egg', '蛋类', 'Eggs', '蛋类', 'Eggs', 144, 13.1, 8.7, 2.8, 0, 320, '茶香浓郁，营养丰富', 'Rich tea aroma, nutritious', TRUE),
('煎蛋', 'Fried Egg', '蛋类', 'Eggs', '蛋类', 'Eggs', 196, 13.6, 15.0, 0.8, 0, 155, '快捷营养，适合早餐', 'Quick and nutritious, good for breakfast', TRUE),
('水煮蛋', 'Boiled Egg', '蛋类', 'Eggs', '蛋类', 'Eggs', 147, 13.3, 8.8, 2.8, 0, 131, '营养保留完整，易消化', 'Retains full nutrition, easy to digest', TRUE),
('炒蛋', 'Scrambled Egg', '蛋类', 'Eggs', '蛋类', 'Eggs', 167, 12.9, 11.5, 2.9, 0, 176, '口感松软，营养丰富', 'Soft texture, nutritious', TRUE),

-- 奶制品 (15条)
('纯牛奶', 'Whole Milk', '奶制品', 'Dairy', '牛奶', 'Milk', 66, 3.0, 3.2, 5.0, 0, 50, '优质蛋白和钙质来源', 'Good source of quality protein and calcium', TRUE),
('脱脂牛奶', 'Skim Milk', '奶制品', 'Dairy', '牛奶', 'Milk', 35, 3.4, 0.1, 5.0, 0, 52, '低脂高蛋白，适合减脂', 'Low fat high protein, good for weight loss', TRUE),
('低脂牛奶', 'Low-fat Milk', '奶制品', 'Dairy', '牛奶', 'Milk', 50, 3.3, 1.5, 5.0, 0, 51, '脂肪含量适中，营养均衡', 'Moderate fat content, nutritionally balanced', TRUE),
('酸奶', 'Yogurt', '奶制品', 'Dairy', '发酵奶', 'Fermented Milk', 72, 2.5, 2.7, 9.3, 0, 47, '富含益生菌，促进消化', 'Rich in probiotics, aids digestion', TRUE),
('希腊酸奶', 'Greek Yogurt', '奶制品', 'Dairy', '发酵奶', 'Fermented Milk', 97, 9.0, 5.0, 3.6, 0, 36, '高蛋白低糖，浓稠顺滑', 'High protein low sugar, thick and creamy', TRUE),
('奶酪', 'Cheddar Cheese', '奶制品', 'Dairy', '奶酪', 'Cheese', 402, 23.3, 33.3, 3.1, 0, 621, '高蛋白高钙，营养密度高', 'High protein high calcium, nutrient dense', TRUE),
('马苏里拉奶酪', 'Mozzarella Cheese', '奶制品', 'Dairy', '奶酪', 'Cheese', 280, 19.9, 21.6, 2.2, 0, 486, '拉丝效果好，富含钙质', 'Good for melting, rich in calcium', TRUE),
('奶油奶酪', 'Cream Cheese', '奶制品', 'Dairy', '奶酪', 'Cheese', 342, 5.9, 34.2, 4.1, 0, 321, '质地柔软，口感细腻', 'Soft texture, smooth taste', TRUE),
('芝士片', 'Cheese Slices', '奶制品', 'Dairy', '奶酪', 'Cheese', 303, 18.0, 25.2, 1.3, 0, 1242, '方便食用，富含钙质', 'Convenient to use, rich in calcium', TRUE),
('羊奶', 'Goat Milk', '奶制品', 'Dairy', '其他奶', 'Other Milk', 69, 3.6, 4.1, 4.5, 0, 50, '易消化，营养丰富', 'Easy to digest, nutritious', TRUE),
('水牛奶', 'Buffalo Milk', '奶制品', 'Dairy', '其他奶', 'Other Milk', 97, 3.7, 6.9, 5.2, 0, 52, '脂肪和蛋白质含量高', 'High in fat and protein', TRUE),
('奶粉', 'Milk Powder', '奶制品', 'Dairy', '奶制品', 'Dairy Products', 502, 25.5, 26.5, 38.4, 0, 400, '便于储存，营养浓缩', 'Easy to store, concentrated nutrition', TRUE),
('炼乳', 'Condensed Milk', '奶制品', 'Dairy', '奶制品', 'Dairy Products', 321, 7.9, 8.7, 54.4, 0, 127, '甜度高，用于烘焙和饮品', 'High sweetness, used in baking and drinks', TRUE),
('黄油', 'Butter', '奶制品', 'Dairy', '奶制品', 'Dairy Products', 717, 0.9, 81.1, 0.1, 0, 11, '富含维生素A和D', 'Rich in vitamins A and D', TRUE),
('淡奶油', 'Whipping Cream', '奶制品', 'Dairy', '奶制品', 'Dairy Products', 345, 2.1, 36.1, 2.8, 0, 38, '脂肪含量高，口感细腻', 'High fat content, smooth texture', TRUE),

-- 豆制品 (15条)
('豆腐', 'Tofu', '豆制品', 'Soy Products', '豆制品', 'Soy Products', 81, 8.1, 3.7, 4.2, 0.4, 7, '优质植物蛋白，富含钙质', 'Quality plant protein, rich in calcium', TRUE),
('嫩豆腐', 'Soft Tofu', '豆制品', 'Soy Products', '豆制品', 'Soy Products', 47, 4.8, 2.4, 1.9, 0.1, 7, '口感细腻，水分含量高', 'Smooth texture, high water content', TRUE),
('老豆腐', 'Firm Tofu', '豆制品', 'Soy Products', '豆制品', 'Soy Products', 98, 10.6, 4.8, 4.3, 0.4, 8, '质地紧实，蛋白质含量高', 'Firm texture, high protein content', TRUE),
('豆腐干', 'Dried Tofu', '豆制品', 'Soy Products', '豆制品', 'Soy Products', 140, 16.2, 3.6, 11.5, 0.7, 25, '营养密度高，便于储存', 'Nutrient dense, easy to store', TRUE),
('豆腐皮', 'Tofu Skin', '豆制品', 'Soy Products', '豆制品', 'Soy Products', 409, 44.6, 17.4, 18.8, 0.2, 23, '高蛋白，富含钙和铁', 'High protein, rich in calcium and iron', TRUE),
('腐竹', 'Dried Beancurd Stick', '豆制品', 'Soy Products', '豆制品', 'Soy Products', 459, 44.6, 21.7, 22.3, 1.0, 26, '营养浓缩，蛋白质丰富', 'Concentrated nutrition, rich in protein', TRUE),
('豆浆', 'Soy Milk', '豆制品', 'Soy Products', '豆制品', 'Soy Products', 54, 3.0, 1.8, 4.5, 1.1, 3, '植物蛋白饮品，易消化', 'Plant protein drink, easy to digest', TRUE),
('豆腐脑', 'Tofu Pudding', '豆制品', 'Soy Products', '豆制品', 'Soy Products', 15, 1.9, 0.8, 0.3, 0.1, 2, '质地嫩滑，营养丰富', 'Smooth texture, nutritious', TRUE),
('臭豆腐', 'Stinky Tofu', '豆制品', 'Soy Products', '豆制品', 'Soy Products', 130, 8.1, 8.0, 7.2, 0.4, 890, '发酵食品，特殊风味', 'Fermented food, unique flavor', TRUE),
('豆豉', 'Fermented Black Beans', '豆制品', 'Soy Products', '豆制品', 'Soy Products', 180, 16.0, 8.2, 15.8, 6.8, 6800, '发酵调味品，富含蛋白质', 'Fermented seasoning, rich in protein', TRUE),
('纳豆', 'Natto', '豆制品', 'Soy Products', '豆制品', 'Soy Products', 212, 16.9, 11.0, 12.6, 5.4, 2, '日式发酵食品，富含维生素K2', 'Japanese fermented food, rich in vitamin K2', TRUE),
('毛豆', 'Edamame', '豆制品', 'Soy Products', '豆制品', 'Soy Products', 125, 11.0, 5.0, 10.5, 4.0, 1, '新鲜大豆，富含蛋白质和膳食纤维', 'Fresh soybeans, rich in protein and fiber', TRUE),
('黄豆', 'Soybeans', '豆制品', 'Soy Products', '豆制品', 'Soy Products', 359, 35.0, 16.0, 34.2, 15.5, 2, '完全蛋白质，营养价值高', 'Complete protein, high nutritional value', TRUE),
('黑豆', 'Black Beans', '豆制品', 'Soy Products', '豆制品', 'Soy Products', 381, 36.0, 15.9, 33.6, 10.2, 3, '富含花青素和蛋白质', 'Rich in anthocyanins and protein', TRUE),
('红豆', 'Red Beans', '豆制品', 'Soy Products', '豆制品', 'Soy Products', 324, 20.2, 0.6, 63.4, 7.7, 2, '富含膳食纤维，利水消肿', 'Rich in dietary fiber, diuretic effect', TRUE),

-- 坚果 (10条)
('核桃', 'Walnut', '坚果', 'Nuts', '坚果', 'Nuts', 654, 15.2, 65.2, 13.7, 9.5, 2, '富含Omega-3和维生素E', 'Rich in Omega-3 and vitamin E', TRUE),
('杏仁', 'Almond', '坚果', 'Nuts', '坚果', 'Nuts', 579, 21.2, 49.9, 21.7, 12.5, 1, '高蛋白高纤维，营养价值高', 'High protein high fiber, highly nutritious', TRUE),
('腰果', 'Cashew', '坚果', 'Nuts', '坚果', 'Nuts', 552, 18.2, 36.7, 41.0, 3.3, 12, '口感细腻，富含矿物质', 'Smooth texture, rich in minerals', TRUE),
('开心果', 'Pistachio', '坚果', 'Nuts', '坚果', 'Nuts', 562, 20.2, 45.3, 27.5, 10.6, 1, '富含B族维生素和矿物质', 'Rich in B vitamins and minerals', TRUE),
('榛子', 'Hazelnut', '坚果', 'Nuts', '坚果', 'Nuts', 628, 14.9, 60.5, 16.7, 9.7, 0, '富含维生素E和不饱和脂肪酸', 'Rich in vitamin E and unsaturated fatty acids', TRUE),
('夏威夷果', 'Macadamia', '坚果', 'Nuts', '坚果', 'Nuts', 718, 7.9, 75.8, 13.8, 8.6, 5, '脂肪含量高，口感香浓', 'High fat content, rich flavor', TRUE),
('花生', 'Peanut', '坚果', 'Nuts', '坚果', 'Nuts', 567, 26.2, 48.7, 16.1, 8.5, 18, '富含蛋白质和不饱和脂肪', 'Rich in protein and unsaturated fat', TRUE),
('瓜子', 'Sunflower Seeds', '坚果', 'Nuts', '坚果', 'Nuts', 616, 23.9, 49.9, 13.1, 4.5, 5, '富含维生素E和叶酸', 'Rich in vitamin E and folate', TRUE),
('南瓜子', 'Pumpkin Seeds', '坚果', 'Nuts', '坚果', 'Nuts', 574, 30.2, 49.1, 4.7, 6.5, 7, '富含锌和镁，保护前列腺', 'Rich in zinc and magnesium, protects prostate', TRUE),
('松子', 'Pine Nuts', '坚果', 'Nuts', '坚果', 'Nuts', 698, 13.7, 68.4, 13.1, 3.7, 2, '富含不饱和脂肪酸，香味独特', 'Rich in unsaturated fatty acids, unique aroma', TRUE),

-- 饮品 (10条)
('绿茶', 'Green Tea', '饮品', 'Beverages', '茶类', 'Tea', 1, 0, 0, 0.3, 0, 1, '富含茶多酚，抗氧化', 'Rich in polyphenols, antioxidant', TRUE),
('红茶', 'Black Tea', '饮品', 'Beverages', '茶类', 'Tea', 1, 0, 0, 0.3, 0, 1, '温和养胃，香气浓郁', 'Gentle on stomach, rich aroma', TRUE),
('乌龙茶', 'Oolong Tea', '饮品', 'Beverages', '茶类', 'Tea', 1, 0, 0, 0.3, 0, 1, '半发酵茶，助消化降脂', 'Semi-fermented tea, aids digestion and reduces fat', TRUE),
('普洱茶', 'Pu-erh Tea', '饮品', 'Beverages', '茶类', 'Tea', 1, 0.1, 0, 0.2, 0, 2, '发酵茶，降脂减肥', 'Fermented tea, reduces fat and aids weight loss', TRUE),
('黑咖啡', 'Black Coffee', '饮品', 'Beverages', '咖啡', 'Coffee', 2, 0.1, 0, 0.5, 0, 2, '提神醒脑，促进代谢', 'Refreshing, boosts metabolism', TRUE),
('拿铁咖啡', 'Latte', '饮品', 'Beverages', '咖啡', 'Coffee', 54, 3.0, 2.0, 6.0, 0, 50, '咖啡加牛奶，口感醇厚', 'Coffee with milk, smooth taste', TRUE),
('橙汁', 'Orange Juice', '饮品', 'Beverages', '果汁', 'Juice', 45, 0.7, 0.2, 10.4, 0.2, 1, '富含维生素C，鲜榨为佳', 'Rich in vitamin C, best freshly squeezed', TRUE),
('苹果汁', 'Apple Juice', '饮品', 'Beverages', '果汁', 'Juice', 46, 0.1, 0.1, 11.3, 0.2, 4, '清甜可口，富含果糖', 'Sweet and refreshing, rich in fructose', TRUE),
('西瓜汁', 'Watermelon Juice', '饮品', 'Beverages', '果汁', 'Juice', 30, 0.6, 0.2, 7.6, 0.4, 1, '解暑利尿，水分充足', 'Cooling and diuretic, high water content', TRUE),
('柠檬水', 'Lemon Water', '饮品', 'Beverages', '其他', 'Others', 6, 0.1, 0, 1.5, 0, 1, '富含维生素C，促进消化', 'Rich in vitamin C, aids digestion', TRUE);
