-- 插入健康打卡测试数据（使用实际存在的用户）

-- 用户53 - 打卡频率高（几乎每天）
INSERT INTO health_records (user_id, record_date, weight, exercise_duration, exercise_type, sleep_hours, sleep_quality, mood, notes, created_at, updated_at)
SELECT 
    53,
    DATE_SUB(CURDATE(), INTERVAL n DAY),
    ROUND(70 + (RAND() * 2 - 1), 1),
    FLOOR(30 + RAND() * 60),
    CASE FLOOR(RAND() * 4) WHEN 0 THEN '跑步' WHEN 1 THEN '游泳' WHEN 2 THEN '健身' ELSE '瑜伽' END,
    ROUND(7 + RAND() * 2, 1),
    CASE FLOOR(RAND() * 4) WHEN 0 THEN 'excellent' WHEN 1 THEN 'good' WHEN 2 THEN 'fair' ELSE 'good' END,
    CASE FLOOR(RAND() * 4) WHEN 0 THEN 'excellent' WHEN 1 THEN 'good' WHEN 2 THEN 'fair' ELSE 'good' END,
    '每日健康记录',
    NOW(),
    NOW()
FROM (SELECT 0 n UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION SELECT 25 UNION SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29) numbers;

-- 用户54 - 打卡频率中等（每2-3天）
INSERT INTO health_records (user_id, record_date, weight, exercise_duration, exercise_type, sleep_hours, sleep_quality, mood, notes, created_at, updated_at)
SELECT 54, DATE_SUB(CURDATE(), INTERVAL n DAY), ROUND(65 + (RAND() * 2 - 1), 1), FLOOR(20 + RAND() * 40), '跑步', ROUND(6.5 + RAND() * 2, 1), 'good', 'good', '健康打卡', NOW(), NOW()
FROM (SELECT 0 n UNION SELECT 2 UNION SELECT 4 UNION SELECT 6 UNION SELECT 8 UNION SELECT 10 UNION SELECT 12 UNION SELECT 14 UNION SELECT 16 UNION SELECT 18 UNION SELECT 20 UNION SELECT 22 UNION SELECT 24 UNION SELECT 26 UNION SELECT 28) numbers;

-- 用户55-69的打卡数据
INSERT INTO health_records (user_id, record_date, weight, exercise_duration, exercise_type, sleep_hours, sleep_quality, mood, notes, created_at, updated_at)
SELECT 55 + (n % 15) as user_id, DATE_SUB(CURDATE(), INTERVAL n DIV 15 DAY), ROUND(60 + RAND() * 20, 1), FLOOR(20 + RAND() * 60), CASE FLOOR(RAND() * 3) WHEN 0 THEN '跑步' WHEN 1 THEN '健身' ELSE '瑜伽' END, ROUND(6 + RAND() * 3, 1), CASE FLOOR(RAND() * 3) WHEN 0 THEN 'excellent' WHEN 1 THEN 'good' ELSE 'fair' END, CASE FLOOR(RAND() * 3) WHEN 0 THEN 'excellent' WHEN 1 THEN 'good' ELSE 'fair' END, '日常打卡', NOW(), NOW()
FROM (SELECT n FROM (SELECT 0 n UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION SELECT 25 UNION SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29 UNION SELECT 30 UNION SELECT 31 UNION SELECT 32 UNION SELECT 33 UNION SELECT 34 UNION SELECT 35 UNION SELECT 36 UNION SELECT 37 UNION SELECT 38 UNION SELECT 39 UNION SELECT 40 UNION SELECT 41 UNION SELECT 42 UNION SELECT 43 UNION SELECT 44 UNION SELECT 45) t) numbers;

-- 插入饮食打卡测试数据（使用实际food_id）
-- 用户53 - 每天多餐打卡
INSERT INTO diet_records (user_id, food_id, record_date, meal_type, quantity, calories, protein, fat, carbs, notes, created_at, updated_at)
SELECT 
    53,
    CASE meal WHEN 0 THEN 153 WHEN 1 THEN 130 ELSE 12 END,  -- 低脂牛奶/三文鱼/全麦面包
    DATE_SUB(CURDATE(), INTERVAL n DAY),
    CASE meal WHEN 0 THEN 'breakfast' WHEN 1 THEN 'lunch' ELSE 'dinner' END,
    ROUND(100 + RAND() * 100, 2),
    ROUND(300 + RAND() * 200, 2),
    ROUND(15 + RAND() * 20, 2),
    ROUND(10 + RAND() * 15, 2),
    ROUND(40 + RAND() * 30, 2),
    '正常饮食',
    NOW(),
    NOW()
FROM (SELECT 0 n UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION SELECT 25 UNION SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29) days
CROSS JOIN (SELECT 0 meal UNION SELECT 1 UNION SELECT 2) meals;

-- 用户54 - 每天1-2餐打卡
INSERT INTO diet_records (user_id, food_id, record_date, meal_type, quantity, calories, protein, fat, carbs, notes, created_at, updated_at)
SELECT 54, CASE meal WHEN 0 THEN 130 ELSE 57 END, DATE_SUB(CURDATE(), INTERVAL n DAY), CASE meal WHEN 0 THEN 'lunch' ELSE 'dinner' END, ROUND(150 + RAND() * 100, 2), ROUND(400 + RAND() * 200, 2), ROUND(20 + RAND() * 15, 2), ROUND(12 + RAND() * 10, 2), ROUND(50 + RAND() * 30, 2), '健康饮食', NOW(), NOW()
FROM (SELECT 0 n UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20 UNION SELECT 22 UNION SELECT 24 UNION SELECT 26 UNION SELECT 28) days
CROSS JOIN (SELECT 0 meal UNION SELECT 1) meals;

-- 用户55-69的饮食打卡
INSERT INTO diet_records (user_id, food_id, record_date, meal_type, quantity, calories, protein, fat, carbs, notes, created_at, updated_at)
SELECT 55 + (n % 15) as user_id, 10 + (n % 200), DATE_SUB(CURDATE(), INTERVAL n DIV 30 DAY), CASE (n % 3) WHEN 0 THEN 'breakfast' WHEN 1 THEN 'lunch' ELSE 'dinner' END, ROUND(100 + RAND() * 150, 2), ROUND(300 + RAND() * 300, 2), ROUND(15 + RAND() * 20, 2), ROUND(10 + RAND() * 15, 2), ROUND(40 + RAND() * 40, 2), '饮食打卡', NOW(), NOW()
FROM (SELECT n FROM (SELECT 0 n UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION SELECT 25 UNION SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29 UNION SELECT 30 UNION SELECT 31 UNION SELECT 32 UNION SELECT 33 UNION SELECT 34 UNION SELECT 35 UNION SELECT 36 UNION SELECT 37 UNION SELECT 38 UNION SELECT 39 UNION SELECT 40 UNION SELECT 41 UNION SELECT 42 UNION SELECT 43 UNION SELECT 44 UNION SELECT 45 UNION SELECT 46 UNION SELECT 47 UNION SELECT 48 UNION SELECT 49 UNION SELECT 50 UNION SELECT 51 UNION SELECT 52 UNION SELECT 53 UNION SELECT 54 UNION SELECT 55 UNION SELECT 56 UNION SELECT 57 UNION SELECT 58 UNION SELECT 59 UNION SELECT 60 UNION SELECT 61 UNION SELECT 62 UNION SELECT 63 UNION SELECT 64 UNION SELECT 65 UNION SELECT 66 UNION SELECT 67 UNION SELECT 68 UNION SELECT 69 UNION SELECT 70 UNION SELECT 71 UNION SELECT 72 UNION SELECT 73 UNION SELECT 74 UNION SELECT 75 UNION SELECT 76 UNION SELECT 77 UNION SELECT 78 UNION SELECT 79 UNION SELECT 80 UNION SELECT 81 UNION SELECT 82 UNION SELECT 83 UNION SELECT 84 UNION SELECT 85 UNION SELECT 86 UNION SELECT 87 UNION SELECT 88 UNION SELECT 89) t) numbers;
